"use client";

import React, { useState } from "react";

const musicMarkdown = `---
title: AI Generated Music & Synthetic Soundscapes
creator: Varun Daiya
year: 2026
category: Audio Synthesis / Generative Sound
---

# AI Generated Music - Synthetic Soundscapes

## Overview
Explorations in synthetic soundscapes and algorithmic composition. These pieces were generated by leveraging generative neural models to interpret and synthesize complex structural audio patterns.

---

## Audio Tracks & Metadata

### Track 01: Ad Astra Per Aspera
- **Audio/Video Stream**: /ai_music/Ad_Astra_Per_Aspera.mp4
- **Format**: MP4 (H.264 / AAC)
- **Concept & Description**:
  "Like a thin filament in an infinite vacuum, we are small and vulnerable. We broadcast our fire into the dark out of a desperate need to matter. The absolute core of this anthem is Ad astra per aspera. To the stars through difficulties. The ascent is never graceful. We must leave our terrestrial safety behind and push past our own sanity. Brutal hardship is the guaranteed price of admission to the stars."

### Track 02: Everything Falls Into Place
- **Audio/Video Stream**: /ai_music/Everything_Falls_Into_Place.mp4
- **Format**: MP4 (H.264 / AAC)
- **Concept & Description**:
  "We are made of the same stuff as the stars, yet we are just tiny people trying to make sense of our time here. It can feel heavy to realize how small we are compared to the rest of the galaxy. This song is about that strange, beautiful moment when you stop to wonder who you are and why you exist. It is a reminder that even though we are just passing through, there is something special about being part of the universe and finally understanding our own place in it."

---

## Navigation
- Return to Main Research: / (or /?mode=machine)
`;

export default function MusicMachineView() {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(musicMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="container mx-auto max-w-4xl px-4 py-20 font-mono animate-in">
      <div className="mb-6 p-4 rounded-lg bg-accent/10 border border-accent/30 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-2.5 h-2.5 rounded-full bg-accent animate-pulse" />
          <div>
            <div className="text-xs uppercase tracking-wider text-accent font-semibold">
              Machine-Readable Mode Active [Audio Catalog]
            </div>
            <div className="text-xs text-muted/80 mt-0.5">
              Structured raw text transcript & track index for AI Agents.
            </div>
          </div>
        </div>

        <button
          onClick={handleCopy}
          className="text-[11px] px-3 py-1.5 rounded bg-accent/20 border border-accent/40 hover:bg-accent/30 text-white transition-all flex items-center gap-1.5 self-end sm:self-auto"
        >
          {copied ? (
            <>
              <svg className="w-3.5 h-3.5 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              <span>Copied!</span>
            </>
          ) : (
            <>
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              <span>Copy Track Spec</span>
            </>
          )}
        </button>
      </div>

      <div className="bg-[#090912] border border-white/10 rounded-xl overflow-hidden shadow-2xl">
        <div className="flex items-center justify-between px-4 py-3 bg-white/[0.03] border-b border-white/10 text-xs">
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-red-500/80 inline-block" />
            <span className="w-3 h-3 rounded-full bg-yellow-500/80 inline-block" />
            <span className="w-3 h-3 rounded-full bg-green-500/80 inline-block" />
            <span className="ml-2 text-muted/60 text-[11px]">music_catalog.md</span>
          </div>
        </div>

        <div className="p-6 overflow-x-auto text-xs sm:text-sm leading-relaxed text-zinc-300 select-all font-mono whitespace-pre-wrap">
          {musicMarkdown}
        </div>
      </div>
    </div>
  );
}
