import Starfield from "@/components/Starfield";
import Link from "next/link";

const ASSET_PREFIX = '/dev_site';

export default function MusicPage() {
  const tracks = [
    {
      title: "Ad Astra Per Aspera",
      file: `${ASSET_PREFIX}/ai_music/Ad_Astra_Per_Aspera.mp4`,
      description: "Like a thin filament in an infinite vacuum, we are small and vulnerable. We broadcast our fire into the dark out of a desperate need to matter. The absolute core of this anthem is Ad astra per aspera. To the stars through difficulties. The ascent is never graceful. We must leave our terrestrial safety behind and push past our own sanity. Brutal hardship is the guaranteed price of admission to the stars."
    },
    {
      title: "Everything Falls Into Place",
      file: `${ASSET_PREFIX}/ai_music/Everything_Falls_Into_Place.mp4`,
      description: "We are made of the same stuff as the stars, yet we are just tiny people trying to make sense of our time here. It can feel heavy to realize how small we are compared to the rest of the galaxy. This song is about that strange, beautiful moment when you stop to wonder who you are and why you exist. It is a reminder that even though we are just passing through, there is something special about being part of the universe and finally understanding our own place in it."
    }
  ];

  return (
    <main className="container mx-auto max-w-3xl px-6 py-24 sm:px-8 font-body text-foreground selection:bg-accent selection:text-white/90">
      <Starfield />
      
      <Link href="/" className="font-mono text-[10px] tracking-widest text-muted hover:text-accent transition-colors uppercase mb-12 block">
        ← Back to Research
      </Link>

      <section id="music-header" className="mb-24 animate-in">
        <h1 className="font-heading text-5xl font-light tracking-tight text-white/90 mb-6">
          AI Generated Music
        </h1>
        <p className="text-xl font-light leading-relaxed text-muted max-w-2xl">
          Explorations in synthetic soundscapes. These pieces were generated by 
          leveraging generative models to interpret complex structural patterns.
        </p>
      </section>

      <div className="space-y-24">
        {tracks.map((track, i) => (
          <section key={i} className="animate-in" style={{ animationDelay: `${(i + 1) * 200}ms` }}>
            <h2 className="font-heading text-2xl text-white/90 mb-4">{track.title}</h2>
            <div className="aspect-video bg-white/[0.02] border border-white/5 relative overflow-hidden group mb-6">
              <video 
                controls 
                src={track.file} 
                className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity"
              />
            </div>
            <p className="text-muted text-sm font-light leading-relaxed max-w-xl">
              {track.description}
            </p>
          </section>
        ))}
      </div>

      <footer className="mt-48 pb-12 text-center border-t border-white/5 pt-8">
        <span className="font-mono text-[10px] tracking-[0.3em] text-muted/30 uppercase">
          Synthetic Sonics // 2026
        </span>
      </footer>
    </main>
  );
}
